### PR TITLE
Constructors + operator.

### PR DESCRIPTION
**Pull request by gskinner**
Added a constructor for POTraceParams & added params to POTrace constructor. Added thresholdOperator to POTraceParams & support for it in POTrace.

I needed the thresholdOperator so that I could trace opaque portions of an image.

Signed-off-by: Grant Skinner info@gskinner.com

### CODE REVIEW

**Comment by gskinner** [comment]
Wow. The diff is sure not picking up my changes well. Maybe a line-break change?

**Comment by claus** [comment]
Argh. Yeah that looks a lot like a line ending problem. Which is weird because we're both on a Mac. I checked and it seems my line endings are all CR LF, and i think i hadn't set core.autocrlf to true (have you?).

Anyhoooo.. The only thing you changed is adding the thresholdOperator and the POTraceParams constructor?

I can't say i agree with the constructor - you should never have to create an instance of that class, it is created automatically by POTrace, so all you need to do is set potraceInstance.params.someParam = someValue. Or what's your use case?

I'm ok with the additional thresholeOperator parameter.

**Comment by gskinner** [comment]
My use case is being able to do everything quickly:
var potrace:POTrace = new POTrace(new POTraceParams(0x666666, ">", 1000, 1, true, 1), new GraphicsDataBackend(gd));

Also, it would be great if you could document the value ranges and expected results from changing those params. I've been trying to figure it out by playing with the values, and I'm still not sure what they all do, or what values I should be feeding them.

**Comment by claus** [comment]
https://github.com/PowerflasherBR/as3potrace/commit/444c1d2d5a8c5398dc057bcefff674aa57fae031

**Comment by claus** [comment]
For the record, parameters are documented in the original, for example here:
http://potrace.sourceforge.net/potracelib.pdf

**Pull request closed without merging**
